src/main/java/de/samply/share/model/Chart.java
/*
 * Copyright (C) 2015 Working Group on Joint Research,
 * Division of Medical Informatics,
 * Institute of Medical Biometrics, Epidemiology and Informatics,
 * University Medical Center of the Johannes Gutenberg University Mainz
 *
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.share.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.TreeMap;

import org.apache.log4j.Logger;

import com.google.common.base.Joiner;

import de.samply.share.client.core.enums.ChartType;
import de.samply.share.client.core.tables.pojos.ChartDefinition;
import de.samply.share.controller.Messages;
import de.samply.share.model.osse.Attribute;
import de.samply.share.model.osse.Case;
import de.samply.share.model.osse.Container;
import de.samply.share.model.osse.Entity;
import de.samply.share.model.osse.Patient;
import de.samply.share.model.osse.QueryResult;

/**
 *
 */
public class Chart implements Serializable {

    private static final long serialVersionUID = -1259686777416200186L;

    private static final Logger logger = Logger.getLogger(Chart.class);

    private ChartDefinition chartDefinition;
    private String xAsJsonArray;
    private String yAsJsonArray;

    private static final int NOF_HISTOGRAM_CLASSES = 10;
    private static final String AMBIGUOUS_VALUE_KEY = "charts.ambiguousValue";
    private static final String NO_VALUE_KEY = "charts.noValue";

    private HashMap<Patient, ArrayList<String>> valuesByPatients;

    public final void addValue(Patient patient, String value) {
        ArrayList<String> values = valuesByPatients.get(patient);
        if (values != null) {
            values.add(value);
        }
        else {
            values = new ArrayList<>();
            values.add(value);
            valuesByPatients.put(patient, values);
        }
    }

    /**
     * For testing only.
     */
    public Chart() {
        chartDefinition = new ChartDefinition();
        chartDefinition.setType(ChartType.HISTOGRAM);
        valuesByPatients = new HashMap<>();
    }

    public Chart(ChartDefinition chartDefinition, QueryResult queryResult) {
        this.chartDefinition = chartDefinition;
        valuesByPatients = new HashMap<>();

        for (Entity entPatient : queryResult.getEntity()) {
            Patient patient = (Patient) entPatient;
            for (Case _case : patient.getCase()) {
                for (Container container : _case.getContainer()) {
                    addValues(patient, container);
                }
            }
            // if the patient does not have the mdr attribute, remember by
            // putting an empty list
            if (!valuesByPatients.containsKey(patient)) {
                valuesByPatients.put(patient, new ArrayList<String>());
            }
        }

        logger.debug("chart.type is " + chartDefinition.getType());
        switch (chartDefinition.getType()) {
            case HISTOGRAM: setXYForHistogram(); break;
            case PIE: setXYForPieChart(); break;
        }
        logger.debug("chart.xAsJsonArray is " + xAsJsonArray);
        logger.debug("chart.yAsJsonArray is " + yAsJsonArray);

    }

    private void setXYForHistogram() {

        ArrayList<Double> values = new ArrayList<>();
        for (Map.Entry<Patient, ArrayList<String>> patientEntry : valuesByPatients.entrySet()) {
            // take average of values
            double sum = 0;
            boolean nonEmptyValueFound = false;
            for (String value : patientEntry.getValue()) {
                if (value != null && !value.isEmpty()) {
                    // for a bar chart, the values have to be numeric
                    sum += Double.parseDouble(value);
                    nonEmptyValueFound = true;
                }
            }
            if (nonEmptyValueFound) {
                values.add(sum / patientEntry.getValue().size());
            }
        }

        if (!values.isEmpty()) {

            if (values.size() > 1) {
                double minValue = Collections.min(values);
                double maxValue = Collections.max(values);

                double classWidth = (maxValue - minValue) / NOF_HISTOGRAM_CLASSES;

                double[] x = new double[NOF_HISTOGRAM_CLASSES + 1];
                for (int i = 0; i < NOF_HISTOGRAM_CLASSES + 1; ++i) {
                    x[i] = minValue + classWidth * i;
                }

                String[] xValuesAsJsonString = new String[NOF_HISTOGRAM_CLASSES];
                for (int i = 0; i < NOF_HISTOGRAM_CLASSES; ++i) {
                    xValuesAsJsonString[i] = "'" + formatDouble(x[i])
                            + " - " + formatDouble(x[i+1]) + "'";
                }
                xAsJsonArray = "[" + Joiner.on(", ").join(xValuesAsJsonString) + "]";

                Integer[] classCount = new Integer[NOF_HISTOGRAM_CLASSES];
                Arrays.fill(classCount, 0);
                for (double value : values) {
                    int classIndex = (int) ((value - minValue) / classWidth);
                    if (classIndex < NOF_HISTOGRAM_CLASSES) {
                        classCount[classIndex] += 1;
                    }
                    else {
                        classCount[NOF_HISTOGRAM_CLASSES - 1] += 1;
                    }

                }
                yAsJsonArray = "[" + Joiner.on(", ").join(classCount) + "]";
            }
            else {
                xAsJsonArray = "['"+ values.get(0) + "']";
                yAsJsonArray = "[1]";
            }
        }
        else {
            // no data to display
            xAsJsonArray = null;
            xAsJsonArray = null;
        }
    }

    private void setXYForPieChart() {
        // values of the attributes,
        // mapped to the number of patients, where they occur
        TreeMap<String, Integer> countedValues = new TreeMap<>();

        // for each patient
        for (Map.Entry<Patient, ArrayList<String>> patientEntry : valuesByPatients.entrySet()) {

            // determine value
            String value;
            if (patientEntry.getValue().isEmpty()) {
                value = Messages.getString(NO_VALUE_KEY);
            }
            else if ((new HashSet<>(patientEntry.getValue())).size() > 1) {
                // there is more than one value for the attribute
                value = Messages.getString(AMBIGUOUS_VALUE_KEY);
            }
            else { // there are values and they are all the same
                value = patientEntry.getValue().get(0);
            }

            // increment counter for value
            Integer count = countedValues.get(value);
            if (count == null) {
                countedValues.put(value, 1);
            } else {
                countedValues.put(value, count + 1);
            }
        }

        if (countedValues.isEmpty()) {
            xAsJsonArray = null;
            yAsJsonArray = null;
        }
        else {
            // tree map guarantees that values are returned in ascending order of the keys
            xAsJsonArray = "['" + Joiner.on("', '").join(countedValues.keySet()) + "']";
            yAsJsonArray = "[" + Joiner.on(", ").join(countedValues.values()) + "]";
        }

    }

    private static String formatDouble(double aDouble) {
        return String.format("%.1f", aDouble);
    }

    /**
     * Recursively adds values for the chart definition's MDR key (=view field).
     * @param patient the patient from whom the values are
     * @param container a container containing attributes with MDR keys and values
     */
    private void addValues(Patient patient, Container container) {
        for (Attribute attribute : container.getAttribute()) {
            String mdrKey = attribute.getMdrKey();
            if (chartDefinition.getViewField1().equals(mdrKey)) {
                addValue(patient, attribute.getValue().getValue());
            }
        }
        for (Container childContainer : container.getContainer()) {
            addValues(patient, childContainer);
        }
    }

    public String getXAsJsonArray() {
        return xAsJsonArray;
    }

    public String getYAsJsonArray() {
        return yAsJsonArray;
    }

    public boolean isDataAvailable() {
        return xAsJsonArray != null;
    }

    public ChartDefinition getChartDefinition() {
        return chartDefinition;
    }

}

src/main/webapp/resources/samplyShare/changePasswordModal.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:composite="http://java.sun.com/jsf/composite" xmlns:o="http://omnifaces.org/ui" xmlns:c="http://java.sun.com/jsp/jstl/core">

<composite:interface>
</composite:interface>

<composite:implementation>
    <div>
        <h:outputScript>
        function checkPw() {
            var p1 = $('.newPass').val();
            var p2 = $('.newPassRepeat').val();
            console.log('p1: ' + p1 + ' - p2: ' + p2);
            return (p1 == p2);
        }
        </h:outputScript>
            <div class="modal fade" id="changePassword" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <h:form prependId="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel">#{msg['menu.changePassword']}</h4>
                        </div>
                        <div class="modal-body">
                        
                            <div class="container-fluid">
                                <div class="form-group">
                                    <label for="currentPass" class="col-sm-3 control-label">#{msg['modal.oldPassword']}</label>
                                    <div class="col-sm-9">
                                        <h:inputSecret id="currentPass" name="currentPass" value="#{loginController.currentPass}" styleClass="form-control" />
                                    </div>
                                </div>

                                <div class="form-space" />

                                <div class="form-group">
                                    <label for="newPass" class="col-sm-3 control-label">#{msg['modal.newPassword']}</label>
                                    <div class="col-sm-9">
                                        <h:inputSecret id="newPass" name="newPass" value="#{loginController.newPass}" styleClass="form-control newPass" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="newPassRepeat" class="col-sm-3 control-label">#{msg['modal.newPasswordRepeat']}</label>
                                    <div class="col-sm-9">
                                        <h:inputSecret id="newPassRepeat" name="newPassRepeat" value="#{loginController.newPassRepeat}"
                                            styleClass="form-control newPassRepeat" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-9">
                                        <o:messages escape="false" id="messagesPass" showDetail="true" var="message">
                                            <div class="#{wu:getAlertClasses(message.severity)}" role="alert">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                <h4>#{message.summary}</h4>
                                                <p>#{message.detail}</p>
                                            </div>
                                        </o:messages>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">#{msg['modal.cancel']}</button>
                                <h:commandLink styleClass="btn btn-success" value="" id="changePassword"
                                     onclick="checkPw()">
                                    <f:ajax listener="#{loginController.changePassword}" execute="@form" render="@form" />
                                    <i class="fa fa-save fa-fw" /> #{msg['menu.changePassword']}
                                </h:commandLink>
                        </div>
                    </div>
                </div>
</h:form>
            </div>
    </div>
</composite:implementation>

</html>

src/main/webapp/resources/samplyShare/chart.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"  
                xmlns:o="http://omnifaces.org/ui"
                xmlns:composite="http://java.sun.com/jsf/composite"
                xmlns:sw="http://java.sun.com/jsf/composite/samplyShare">

    <composite:interface>
        <composite:attribute name="chart" type="de.samply.share.model.Chart" 
                             required="true" />
        <composite:attribute name="index" required="true" 
                             type="java.lang.Integer"/>
    </composite:interface>

    <composite:implementation>
        <h:outputStylesheet name="css/jquery.jqplot.min.css" />
        <h:outputScript name="js/jqplot/jquery.jqplot.min.js" target="head" />
        <h:outputScript name="js/jqplot/jqplot.pieRenderer.min.js" target="head" />
        <h:outputScript name="js/jqplot/jqplot.categoryAxisRenderer.min.js" target="head" />
        <h:outputScript name="js/jqplot/jqplot.pointLabels.min.js" target="head" />
        <h:outputScript name="js/jqplot/jqplot.barRenderer.min.js" target="head"/>
        <h:outputScript name="js/jqplot/jqplot.canvasTextRenderer.min.js" target="head"/>
        <h:outputScript name="js/jqplot/jqplot.canvasAxisLabelRenderer.min.js" target="head"/>
        <h:outputScript name="js/jqplot/jqplot.canvasAxisTickRenderer.min.js" target="head"/>
        <h:outputScript name="js/charts.js" target="head" />

        <ui:fragment rendered="#{cc.attrs.chart ne null}">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <div style="float:right;">
                            <h:commandLink action="#{chartDefinitionBean.editChartDefinition(cc.attrs.index)}">
                                <i class="fa fa-edit" />
                            </h:commandLink>
                            <h:outputLink value="#"
                                          onclick="showDeleteChartModal#{cc.attrs.index}();return false;">
                                <i class="fa fa-trash" />    
                            </h:outputLink>
                        </div>
                        <h:outputText value="#{MdrDataElementBean.getLabelText(cc.attrs.chart.chartDefinition.viewField1)}"/>
                    </h3>
                </div>
                <div class="panel-body">
                    <ui:fragment rendered="#{cc.attrs.chart.dataAvailable}">
                        <div id="chartDiv#{cc.attrs.index}"/>
                        <h:outputScript rendered="#{cc.attrs.chart.chartDefinition.type eq ChartType.PIE}">
                            makePieChart("chartDiv#{cc.attrs.index}", #{cc.attrs.chart.getXAsJsonArray()}, #{cc.attrs.chart.getYAsJsonArray()});
                        </h:outputScript>
                        <h:outputScript rendered="#{cc.attrs.chart.chartDefinition.type eq ChartType.HISTOGRAM}">
                            makeBarChart("chartDiv#{cc.attrs.index}", #{cc.attrs.chart.getXAsJsonArray()}, #{cc.attrs.chart.getYAsJsonArray()}, 
                            "#{MdrDataElementBean.getLabelText(cc.attrs.chart.chartDefinition.viewField1)}", "#{msg['charts.nofOccurences']}");
                        </h:outputScript>
                    </ui:fragment>
                    <ui:fragment rendered="#{not cc.attrs.chart.dataAvailable}">
                        <div style="text-align: center; vertical-align: middle">
                            <h:outputText value="#{msg['charts.noChart']}" />
                        </div>
                    </ui:fragment>
                </div>
            </div>
                
            <sw:modal title="#{msg['charts.deleteChartModalTitle']}"
                      modalId="DeleteChartModal#{cc.attrs.index}">
                <f:facet name="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <h:outputFormat value="#{msg['charts.deleteChartText']}">
                                <f:param value="#{MdrDataElementBean.getLabelText(cc.attrs.chart.chartDefinition.viewField1)}" />
                            </h:outputFormat>
                        </div>
                    </div>
                </f:facet>
                <f:facet name="buttons">
                    <h:commandButton class="btn btn-success" 
                                     action="#{chartQueryGroupController.deleteChart(cc.attrs.index)}"
                                     value="#{msg['charts.deleteChart']}" />
                </f:facet>
            </sw:modal>
                
        </ui:fragment>
    </composite:implementation>
</ui:composition>

src/main/webapp/resources/samplyShare/confirmDeletionModal.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:composite="http://java.sun.com/jsf/composite"   >

    <composite:interface>
    </composite:interface>

    <composite:implementation>
        <div>
            <h:form>
                <div class="modal fade" id="exportDefinitionNameModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="myModalLabel">#{msg['export.saveModalTitle']}</h4>
                            </div>
                            <div class="modal-body">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <h:outputText value="#{msg['export.setName']}" />
                                        </div>
                                        <div class="col-lg-12">
                                            <h:inputText value="#{exportController.exportDefinition.name}" styleClass="form-control"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">#{msg['export.cancel']}</button>
                                <h:commandButton class="btn btn-success" 
                                                 action="#{exportController.save()}"
                                                 value="#{msg['export.save']}" />
                            </div>
                        </div>
                    </div>
                </div>
            </h:form>
        </div>
    </composite:implementation>

</html>

src/main/webapp/resources/samplyShare/exportDatepicker.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:composite="http://java.sun.com/jsf/composite" xmlns:o="http://omnifaces.org/ui" xmlns:wu="http://share.samply.de/webutils">

<composite:interface>
    <composite:attribute name="label" required="true" />
    <composite:attribute name="lowerBound" required="true" />
    <composite:attribute name="upperBound" required="true" />
</composite:interface>

<composite:implementation>
    <div class="row">
        <div class="col-md-2 col-md-offset-2">
            <h:outputLabel styleClass="exportDatepickerLabel" value="#{cc.attrs.label}" for="lowerBound" />
        </div>
        <div class="col-md-2">
            <div class="input-group datepicker">
                <h:inputText id="lowerBound" styleClass="form-control" value="#{cc.attrs.lowerBound}">
                    <!-- time zone set to server timezone, so there is no problem with conversion -->
                    <f:convertDateTime timeZone="#{wu:getServerTimeZone()}" pattern="#{view.locale eq 'de' ? 'dd.MM.yyyy' : 'yyyy/MM/dd'}" />
                </h:inputText>
                <span class="input-group-addon"> <span class="fa fa-calendar"></span>
                </span>
            </div>
        </div>
        <div class="col-md-1 exportDatepickerConjunction">#{msg['export.dateConjunction']}</div>
        <div class="col-md-2">
            <div class="input-group datepicker">
                <h:inputText id="upperBound" styleClass="form-control" value="#{cc.attrs.upperBound}">
                    <f:convertDateTime timeZone="#{wu:getServerTimeZone()}" pattern="#{view.locale eq 'de' ? 'dd.MM.yyyy' : 'yyyy/MM/dd'}" />
                </h:inputText>
                <span class="input-group-addon"> <span class="fa fa-calendar"></span>
                </span>
            </div>
        </div>
    </div>
</composite:implementation>
</html>

src/main/webapp/resources/samplyShare/loginPanel.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:o="http://omnifaces.org/ui"
    xmlns:composite="http://java.sun.com/jsf/composite" xmlns:wu="http://share.samply.de/webutils" xmlns:pass="http://xmlns.jcp.org/jsf/passthrough">

<composite:interface>

</composite:interface>

<composite:implementation>
    <div class="formContainer col-md-4 col-md-offset-4">

        <h:form>
            <div class="form-signin">
                <div class="pull-right logo">
                    <span class="titleBlack">OSSE</span><span class="titleDarkBlue">.Share</span>
                    <div class="subtitle">client</div>

                </div>
                <h2 class="form-signin-heading">#{msg['loginPanel.login']}</h2>

                <h:inputText type="text" styleClass="form-control" pass:placeholder="#{msg['loginPanel.username']}" value="#{loginController.user.username}"
                    pass:autofocus="true" />
                <h:inputSecret styleClass="form-control" pass:placeholder="#{msg['loginPanel.password']}" value="#{loginController.user.password}" />

                <h:commandButton styleClass="btn btn-md btn-primary btn-block" value="#{msg['loginPanel.doLogin']}" type="submit"
                    action="#{loginController.login}" />

                <div id="version" style="float: right; position: relative; top: -0.3em;" class="pull-right">
                    <small>#{wu:getVersionString()}</small>
                </div>


            </div>
            <o:messages escape="false" id="messages" showDetail="true" var="message">
                <div class="#{wu:getAlertClasses(message.severity)}" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4>#{message.summary}</h4>
                    <p>#{message.detail}</p>
                </div>
            </o:messages>
        </h:form>

    </div>
</composite:implementation>

</html>

src/main/webapp/resources/samplyShare/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:composite="http://java.sun.com/jsf/composite" xmlns:wu="http://share.samply.de/webutils"
    xmlns:share="http://java.sun.com/jsf/composite/samplyShare">

<composite:interface>
    <composite:attribute name="activePage" type="java.lang.String" />
</composite:interface>

<composite:implementation>
    <h:form>
        <div class="navbar navbar-fixed-top" style="position: absolute !important;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><span class="title">OSSE</span><span class="titleBlue">.Share</span></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <ui:fragment rendered="#{loginController.getLoggedUsername().toLowerCase() != 'admin'}">
                        <li class="#{(cc.attrs.activePage == 'incomingInquiries.xhtml' || cc.attrs.activePage == 'showInquiry.xhtml')  ? 'active' : ''}"><h:outputLink
                                value="incomingInquiries.xhtml">#{msg['menu.inquiries']}</h:outputLink></li>
                        <li
                            class="#{(cc.attrs.activePage == '/exportQueryBuilder.xhtml' || cc.attrs.activePage == '/exportOverview.xhtml' || cc.attrs.activePage == '/exportDefinition.xhtml')  ? 'active' : ''}">
                            <h:link outcome="exportOverview" value="#{msg['menu.dataExport']}" />
                        </li>
                        <li
                            class="#{(cc.attrs.activePage == '/chartGroupQueryBuilder.xhtml' || cc.attrs.activePage == '/chartsOverview.xhtml' || cc.attrs.activePage == '/chartQueryGroup.xhtml' || cc.attrs.activePage == '/chartDefinition.xhtml')  ? 'active' : ''}">
                            <h:link outcome="chartsOverview.xhtml" value="#{msg['charts.menuTitle']}" />
                        </li>
                        </ui:fragment>
                        <ui:fragment rendered="#{loginController.getLoggedUsername().toLowerCase() == 'admin'}">
                            <li class="#{(cc.attrs.activePage == 'configuration.xhtml' || cc.attrs.activePage == 'brokerList.xhtml') ? 'active' : ''}"><h:outputLink
                                    value="configuration.xhtml">#{msg['menu.configuration']}</h:outputLink></li>
                            <li class="#{cc.attrs.activePage == 'logViewer.xhtml' ? 'active' : ''}"><h:outputLink value="logViewer.xhtml">#{msg['menu.log']}</h:outputLink></li>
                        </ui:fragment>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">#{loginController.getLoggedUsername()} <b
                                class="caret"></b>
                        </a>
                            <ul class="dropdown-menu">
                                <li><a href="#" onclick="$('#changePassword').modal();"><i class="fa fa-gear"></i> #{msg['menu.changePassword']}</a></li>
                                <li class="divider"></li>
                                <li class="logoutElement"><h:commandLink action="#{loginController.logout}">
                                        <i class="fa fa-sign-out"></i> #{msg['menu.logout']}</h:commandLink></li>
                            </ul></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </h:form>
    <share:changePasswordModal />
</composite:implementation>
</html>